l4p/tcp: fix missing braces
Fix below compiling error:

    lib/libtle_l4p/tcp_rxtx.c:2434:6: error: this ‘else’ clause
    does not guard... [-Werror=misleading-indentation]
    } else
      ^~~~
    lib/libtle_l4p/tcp_rxtx.c:2437:5: note: ...this statement,
    but the latter is misleadingly indented as if it were guarded by the
    ‘else’
         break;
         ^~~~~

Fixes: 05da2ef1aad2d("l4p:fix tx event raise condition and writev errno when tcp tx-queue is full")

Change-Id: I249da51e5d401671d533f0207031a3d30612e5f9
Signed-off-by: Jianfeng Tan <henry.tjf@antfin.com>