examples/l4fwd: fix compile errors
After below DPDK commit, some offload APIs are changed.
  commit ab3ce1e0c193 ("ethdev: remove old offload API")

This leads to compile errors:
  error: ‘struct rte_eth_rxmode’ has no member named ‘hw_vlan_strip’
     .hw_vlan_strip = 1,
      ^~~~~~~~~~~~~

  error: ‘struct rte_eth_rxmode’ has no member named ‘hw_ip_checksum’
     port_conf.rxmode.hw_ip_checksum = 1;
                     ^

Change-Id: I2bfefca70f17447df2a1cf5d888e543c9ffbaaca
Signed-off-by: Jianfeng Tan <henry.tjf@antfin.com>