examples/l4fwd: fix compile error
After below change in DPDK, we encounter compile error.
  commit 03d8f4710030 ("ethdev: return named opaque type instead of void pointer")

  error: assignment discards ‘const’ qualifier from pointer target
  type [-Werror=discarded-qualifiers]
      cb = rte_eth_add_rx_callback(uprt->id, qid,
         ^

The fix is straight-forward, we add a const qualifier to the variable.

Change-Id: I0121cc2a7559019971645a8433a0b898f845215a
Signed-off-by: Jianfeng Tan <henry.tjf@antfin.com>